services:
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - backend

  api:
    build: ./api
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - backend

  user-auth:
    build: ./user-auth
    container_name: user-auth
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    networks:
      - backend

  user-login:
    build: ./user-login
    container_name: user-login
    ports:
      - "8082:8082"
    depends_on:
      - eureka
    networks:
      - backend

networks:
  backend:
    driver: bridge
