server:
  port: 8082

spring:
  main:
    web-application-type: reactive
  profiles:
    active: test
  application:
    name: USER-LOGIN
  datasource:
    url: jdbc:h2:mem:logindb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
