server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  application:
    name: USER-AUTH
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
